module.exports = {
  single: {
    _bta_c: 'Bronto',
    _bta_tid: 'Bronto',
    _ga: 'Google Analytics',
    _ke: 'Klaviyo',
    dm_i: 'dotdigital',
    ef_id: 'Adobe Advertising Cloud',
    epik: 'Pinterest',
    fbclid: 'Facebook',
    gclid: 'Google AdWords / Google Analytics',
    gclsrc: 'Google DoubleClick',
    gdffi: 'GoDataFeed',
    gdfms: 'GoDataFeed',
    gdftrk: 'GoDataFeed',
    mkwid: 'Marin',
    msclkid: 'Microsoft Advertising',
    pcrid: 'Marin',
    s_kwcid: 'Adobe Analytics',
    sb_referer_host: 'Springbot',
  },
  prefix: {
    _bta_: 'Bronto',
    hsa_: 'Hubspot',
    matomo_: 'Matomo',
    mc_: 'Mailchimp',
    mtm_: 'Matomo',
    piwik_: 'Piwik',
    pk_: 'Piwik',
    redirect_: 'Springbot',
    trk_: 'Listrak',
    utm_: 'Google Analytics',
  },
}
